twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        -  'form/fields.html.twig'
    paths:
        '%kernel.project_dir%/src/MultiStepBundle/Resources/views': MultiStepBundle
        '%kernel.project_dir%/src/AdminBundle/Infrastructure/UI': AdminBundle
        '%kernel.project_dir%/src/AdminBundle/SubBundles/SortingBundle/Infrastructure/UI': SortingBundle
    file_name_pattern: '*.twig'
    globals:
        app_base_path: '%app.base_path%'
        app_public_path: '%app.public_path%'
    cache: '%kernel.cache_dir%/twig'

when@test:
    twig:
        strict_variables: true
